config/routes.rb
Minusdollar::Application.routes.draw do
  resources :enemies

  resources :friendships

  get "home/index"

  resources :pledges

  root :to => 'home#index'
  root :to => 'friendships#index'
  root :to => 'enemies#index'

end

app/models/enemy.rb
class Enemy < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  attr_accessible :amount, :issue_title, :issue_url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/enemies_controller.rb
class EnemiesController < ApplicationController
  # GET /enemies
  # GET /enemies.json
  def index
    @enemies = Enemy.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @enemies }
    end
  end

  # GET /enemies/1
  # GET /enemies/1.json
  def show
    @enemy = Enemy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @enemy }
    end
  end

  # GET /enemies/new
  # GET /enemies/new.json
  def new
    @enemy = Enemy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @enemy }
    end
  end

  # GET /enemies/1/edit
  def edit
    @enemy = Enemy.find(params[:id])
  end

  # POST /enemies
  # POST /enemies.json
  def create
    @enemy = Enemy.new(params[:enemy])

    respond_to do |format|
      if @enemy.save
        format.html { redirect_to @enemy, notice: 'Enemy was successfully created.' }
        format.json { render json: @enemy, status: :created, location: @enemy }
      else
        format.html { render action: "new" }
        format.json { render json: @enemy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /enemies/1
  # PUT /enemies/1.json
  def update
    @enemy = Enemy.find(params[:id])

    respond_to do |format|
      if @enemy.update_attributes(params[:enemy])
        format.html { redirect_to @enemy, notice: 'Enemy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @enemy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enemies/1
  # DELETE /enemies/1.json
  def destroy
    @enemy = Enemy.find(params[:id])
    @enemy.destroy

    respond_to do |format|
      format.html { redirect_to enemies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  # GET /friendships
  # GET /friendships.json
  def index
    @friendships = Friendship.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @friendships }
    end
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show
    @friendship = Friendship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @friendship }
    end
  end

  # GET /friendships/new
  # GET /friendships/new.json
  def new
    @friendship = Friendship.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @friendship }
    end
  end

  # GET /friendships/1/edit
  def edit
    @friendship = Friendship.find(params[:id])
  end

  # POST /friendships
  # POST /friendships.json
  def create
    @friendship = Friendship.new(params[:friendship])

    respond_to do |format|
      if @friendship.save
        format.html { redirect_to @friendship, notice: 'Friendship was successfully created.' }
        format.json { render json: @friendship, status: :created, location: @friendship }
      else
        format.html { render action: "new" }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /friendships/1
  # PUT /friendships/1.json
  def update
    @friendship = Friendship.find(params[:id])

    respond_to do |format|
      if @friendship.update_attributes(params[:friendship])
        format.html { redirect_to @friendship, notice: 'Friendship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    @friendship = Friendship.find(params[:id])
    @friendship.destroy

    respond_to do |format|
      format.html { redirect_to friendships_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  # GET /pledges
  # GET /pledges.json
  def index
    @pledges = Pledge.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pledges }
    end
  end

  # GET /pledges/1
  # GET /pledges/1.json
  def show
    @pledge = Pledge.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pledge }
    end
  end

  # GET /pledges/new
  # GET /pledges/new.json
  def new
    @pledge = Pledge.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pledge }
    end
  end

  # GET /pledges/1/edit
  def edit
    @pledge = Pledge.find(params[:id])
  end

  # POST /pledges
  # POST /pledges.json
  def create
    @pledge = Pledge.new(params[:pledge])

    respond_to do |format|
      if @pledge.save
        format.html { redirect_to @pledge, notice: 'Pledge was successfully created.' }
        format.json { render json: @pledge, status: :created, location: @pledge }
      else
        format.html { render action: "new" }
        format.json { render json: @pledge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pledges/1
  # PUT /pledges/1.json
  def update
    @pledge = Pledge.find(params[:id])

    respond_to do |format|
      if @pledge.update_attributes(params[:pledge])
        format.html { redirect_to @pledge, notice: 'Pledge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pledge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pledges/1
  # DELETE /pledges/1.json
  def destroy
    @pledge = Pledge.find(params[:id])
    @pledge.destroy

    respond_to do |format|
      format.html { redirect_to pledges_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enemies_helper.rb
module EnemiesHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/views/enemies/_form.html.erb
<%= form_for(@enemy) do |f| %>
  <% if @enemy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enemy.errors.count, "error") %> prohibited this enemy from being saved:</h2>

      <ul>
      <% @enemy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/enemies/edit.html.erb
<h1>Editing enemy</h1>

<%= render 'form' %>

<%= link_to 'Show', @enemy %> |
<%= link_to 'Back', enemies_path %>

app/views/enemies/index.html.erb
<h1>Listing enemies</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @enemies.each do |enemy| %>
  <tr>
    <td><%= link_to 'Show', enemy %></td>
    <td><%= link_to 'Edit', edit_enemy_path(enemy) %></td>
    <td><%= link_to 'Destroy', enemy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Enemy', new_enemy_path %>

app/views/enemies/new.html.erb
<h1>New enemy</h1>

<%= render 'form' %>

<%= link_to 'Back', enemies_path %>

app/views/enemies/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_enemy_path(@enemy) %> |
<%= link_to 'Back', enemies_path %>

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<h1>Listing friendships</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @friendships.each do |friendship| %>
  <tr>
    <td><%= link_to 'Show', friendship %></td>
    <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
    <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Minusdollar</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pledges/_form.html.erb
<%= form_for(@pledge) do |f| %>
  <% if @pledge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pledge.errors.count, "error") %> prohibited this pledge from being saved:</h2>

      <ul>
      <% @pledge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :issue_url %><br />
    <%= f.text_field :issue_url %>
  </div>
  <div class="field">
    <%= f.label :issue_title %><br />
    <%= f.text_field :issue_title %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pledges/edit.html.erb
<h1>Editing pledge</h1>

<%= render 'form' %>

<%= link_to 'Show', @pledge %> |
<%= link_to 'Back', pledges_path %>

app/views/pledges/index.html.erb
<h1>Listing pledges</h1>

<table>
  <tr>
    <th>Issue url</th>
    <th>Issue title</th>
    <th>Amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pledges.each do |pledge| %>
  <tr>
    <td><%= pledge.issue_url %></td>
    <td><%= pledge.issue_title %></td>
    <td><%= pledge.amount %></td>
    <td><%= link_to 'Show', pledge %></td>
    <td><%= link_to 'Edit', edit_pledge_path(pledge) %></td>
    <td><%= link_to 'Destroy', pledge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pledge', new_pledge_path %>

app/views/pledges/new.html.erb
<h1>New pledge</h1>

<%= render 'form' %>

<%= link_to 'Back', pledges_path %>

app/views/pledges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Issue url:</b>
  <%= @pledge.issue_url %>
</p>

<p>
  <b>Issue title:</b>
  <%= @pledge.issue_title %>
</p>

<p>
  <b>Amount:</b>
  <%= @pledge.amount %>
</p>


<%= link_to 'Edit', edit_pledge_path(@pledge) %> |
<%= link_to 'Back', pledges_path %>